apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "jfrog-demo"
spec:
  stages:
    - name: staging
      sequences:
      - name: release
        tasks:
        - name: deployment
        - name: test
        - name: evaluation
          properties:
            timeframe: 5m
    - name: production123
      sequences:
      - name: release
        triggeredOn:
        - event: staging.release.finished
        tasks:
        - name: approval
          properties:
            pass: manual
            warning: manual
