apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "jfrog-demo"
spec:
  stages:
    - name: staging
      sequences:
      - name: release
        tasks:
        - name: deployment
        - name: test
        - name: evaluation
          properties:
            timeframe: 5m
        - name: notify
