apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.triggered
      requests:
        - curl --request POST --data
          '{"IMAGE_TAG":"{{.data.release.imageTag}}"}'
          https://{{.env.secret_jfrogdemo_jfrogdemowebhookdeploy}}
      envFrom:
        - name: secret_jfrogdemo_jfrogdemowebhookdeploy
          secretRef:
            name: jfrog-demo
            key: jfrogdemo_webhook_deploy
      subscriptionID: 75851814-992a-40b6-94ad-198d25953cd2
      sendFinished: true
