apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.triggered
      requests:
        - "curl --header 'Content-type: application/json' --request POST --data
          '{\"imageTag\":\"{{.data.release.imageTag}}\",\"type\":\"{{.type}}\",\
          \"project\":\"{{.data.project}}\",\"service\":\"{{.data.service}}\",\
          \"stage\":\"{{.data.stage}}\",\"shkeptncontext\":\"{{.shkeptncontext}}\
          \",\"id\":\"{{.id}}\"}'
          https://{{.env.secret_jfrogdemo_jfrogdemowebhookdeploy}}"
      envFrom:
        - name: secret_jfrogdemo_jfrogdemowebhookdeploy
          secretRef:
            name: jfrog-demo
            key: jfrogdemo_webhook_deploy
      subscriptionID: 75851814-992a-40b6-94ad-198d25953cd2
      sendFinished: false
    - type: sh.keptn.event.test.triggered
      requests:
        - "curl --header 'Content-type: application/json' --request POST --data
          '{\"type\":\"{{.type}}\",\"project\":\"{{.data.project}}\",\"service\
          \":\"{{.data.service}}\",\"stage\":\"{{.data.stage}}\",\"shkeptnconte\
          xt\":\"{{.shkeptncontext}}\",\"id\":\"{{.id}}\"}'
          https://{{.env.secret_jfrogdemo_jfrogdemowebhooktest}}"
      envFrom:
        - name: secret_jfrogdemo_jfrogdemowebhooktest
          secretRef:
            name: jfrog-demo
            key: jfrogdemo_webhook_test
      subscriptionID: c5289298-cd94-442c-b379-5596cb3064d6
      sendFinished: false
    - type: sh.keptn.event.evaluation.triggered
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"jiraKey\":\"{{.data.release.jiraKey}}\",\"jiraMessage\":\"SLO
          Evaluation for Project: {{.data.project}} Stage: {{.data.stage}}
          Service:
          {{.data.service}}\",\"result\":\"{{.data.result}}\",\"bridge\":\"{{.e\
          nv.secret_bridge_url}}/evaluation/{{.shkeptncontext}}/{{.data.stage}}\
          \"}'
          https://automation.atlassian.com/pro/hooks/9be53cf516a9e3e0af08d3bd0c\
          c215d77c0b985e"
      envFrom:
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
      subscriptionID: 1d8276f4-6fa2-4f0a-8f5e-23dfd00bd0f0
      sendFinished: true
